version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portfolio-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mzeb419mpvg9"
s3_prefix = "portfolio-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
