AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-app

  Sample SAM Template for portfolio-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: authentication/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_PW: "PRnGBDeoZTxvgoqO"
          JWT_SECRET: "FwyGK@pyCThOBNsGebLZ"
      Events:
        Health: 
          Type: Api
          Properties:
            Path: /auth/health
            Method: get
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
        Verify:
          Type: Api
          Properties: 
            Path: /auth/verify
            Method: post

